version: "3.9"

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    tty: true
    # command: pnpm run dev

  graphql-engine:
    depends_on:
      - postgres
    container_name: hasura
    image: hasura/graphql-engine:v2.1.1
    ports:
      - 8080:8080
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgrespassword
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

volumes:
  db_data:
